name: Installation
on: 
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: ebookipedia/install@main
        with:
            url: ${{github.event.repository.description}}
      - run: ls

